# Generated by Django 6.0.6 on 2026-06-06 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_rfqitem'),
        ('vendors', '0002_vendor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQVendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('VIEWED', 'Viewed'), ('RESPONDED', 'Responded')], default='INVITED', max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_rfq_vendors', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='rfq.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rfqs', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
