# Generated by Django 6.0.6 on 2026-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('MANAGER', 'Manager'), ('VENDOR', 'Vendor')], default='ADMIN', max_length=30),
        ),
    ]
